/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DComm_DCommAPI */

#ifndef _Included_DComm_DCommAPI
#define _Included_DComm_DCommAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef DComm_DCommAPI_DCOMM_OK
#define DComm_DCommAPI_DCOMM_OK 0L
/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_config_from_file
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_DComm_1config_1from_1file
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DComm_DCommAPI
 * Method:    process_msg_get
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_process_1msg_1get
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

/*
 * Class:     DComm_DCommAPI
 * Method:    process_msg_set
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_process_1msg_1set
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     DComm_DCommAPI
 * Method:    process_msg_notify
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_process_1msg_1notify
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     DComm_DCommAPI
 * Method:    process_msg_answer_get
 * Signature: (IIII[B)V
 */
JNIEXPORT void JNICALL Java_DComm_DCommAPI_process_1msg_1answer_1get
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     DComm_DCommAPI
 * Method:    process_msg_exec
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_process_1msg_1exec
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     DComm_DCommAPI
 * Method:    process_msg_error
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_DComm_DCommAPI_process_1msg_1error
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_DComm_1start
  (JNIEnv *, jobject);

/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DComm_DCommAPI_DComm_1stop
  (JNIEnv *, jobject);

/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_process_msg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_DComm_1process_1msg
  (JNIEnv *, jobject);

/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_send_GET
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_DComm_1send_1GET
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_send_SET
 * Signature: (IIIII[B)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_DComm_1send_1SET
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_send_NOTIFY
 * Signature: (III[B)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_DComm_1send_1NOTIFY
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray);

/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_send_EXEC
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_DComm_1send_1EXEC
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_send_MSG
 * Signature: (III[B)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_DComm_1send_1MSG
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray);

/*
 * Class:     DComm_DCommAPI
 * Method:    DComm_print_error
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_DComm_DCommAPI_DComm_1print_1error
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
