all: escritor leitor

escritor: escritor.c escritor.h header.h
	gcc -g -Wall -pedantic -ansi -o escritor escritor.c 

leitor: leitor.c leitor.h header.h
	gcc -Wall -pedantic -ansi -o leitor leitor.c 
